### ISSUE TITLE
Request for informations about Specialist

### ISSUE THREAD

**Issue by ojaksch** [MiSTer-devel/Specialist_MiSTer#2]
For our project "tty2oled" (https://misterfpga.org/viewtopic.php?f=9&t=1887 and https://venice1200.github.io/MiSTer_tty2oled_Pictures/) the only missing picture for non-arcade cores is the one for the Specialist. I find almost nothing about it - no usable pictures, no informative text, nothing.
Do you, as the father of this core, have some informations/pictures/material about about this system I could use to complete the list?

**Comment by sorgelig** [comment]
may be this will help you:
https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D1%81%D1%82_(%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80)

**Comment by ojaksch** [comment]
That is the only usable information I already found, but thanks anyway and I did my best to squeeze it onto a 256x64 size. Hooray, no cores without image left!

![SPMX](https://user-images.githubusercontent.com/17717333/146570126-0f337660-3f71-405c-bb10-94334c4411b3.png)
